export const leadFieldsSchema = {
  full_Name: {
    label: 'Full Name',
    type: 'text',
    required: true,
    placeholder: 'Enter full name',
  },
  mobile: {
    label: 'Mobile',
    type: 'mobile',
    required: true,
    placeholder: 'Enter mobile number',
  },
  email: { label: 'Email', type: 'email', placeholder: 'Enter email address' },
  category: {
    label: 'Category',
    type: 'select',
    options: [
      'Loan',
      'Insurance',
      'Auditing Services',
      'Mutual Fund',
      'Financial Consultation',
      'Fianancial Planning',
      'Creditcard Consultation',
      'Investment Consultation',
      'Tax Consultation',
      'Other',
    ],
    required: true,
    placeholder: 'Select a category',
  },
  sub_category: {
    label: 'Sub Category',
    type: 'text',
    placeholder: 'Enter sub-category',
  },
  mobileTwo: {
    label: 'Mobile 2',
    type: 'mobile',
    required: false,
    placeholder: 'Enter mobile 2 (optional)',
  },
  gender: {
    label: 'Gender',
    type: 'select',
    options: ['Male', 'Female', 'Transgender'],
    placeholder: 'Enter gender',
  },
  dob: { label: 'Date of Birth', type: 'text', placeholder: 'DD-MM-YYYY' },
  age: { label: 'Age', type: 'text', placeholder: 'Enter age' },
  annualIncome: {
    label: 'Annual Income',
    type: 'text',
    placeholder: 'Enter annual income',
  },
  employmentType: {
    label: 'Employment Type',
    type: 'select',
    options: [
      'Salaried',
      'Business',
      'House Wife',
      'Student',
      'Retired',
      'Other',
    ],
    placeholder: 'Enter employment type',
  },
  lead_from: {
    label: 'Lead From',
    type: 'select',
    options: [
      'Website',
      'Phone',
      'Email',
      'Walk-in',
      'Reference',
      'Social Media',
      'Other',
    ],
    placeholder: 'Enter lead source',
  },
  referral_id: {
    label: 'Referred By',
    type: 'combo',
    placeholder: 'Enter referred by',
  },
  street: {
    label: 'Street',
    type: 'text',
    placeholder: 'Enter street address',
  },
  city: { label: 'City', type: 'text', placeholder: 'Enter city' },
  zipCode: { label: 'Zip Code', type: 'text', placeholder: 'Enter zip code' },
  state: { label: 'State', type: 'text', placeholder: 'Enter state' },
  country: { label: 'Country', type: 'text', placeholder: 'Enter country' },
  panNumber: {
    label: 'PAN Number',
    type: 'text',
    required: true,
    conditional: (data: { category: string }) =>
      data.category === 'Auditing Services',
    placeholder: 'Enter PAN number',
  },
  aadharNumber: {
    label: 'Aadhar Number',
    type: 'text',
    conditional: (data: { category: string }) =>
      data.category === 'Auditing Services',
    placeholder: 'Enter Aadhar number',
  },
  filingType: {
    label: 'Filing Type',
    type: 'text',
    conditional: (data: { category: string }) =>
      data.category === 'Auditing Services',
    placeholder: 'Enter filing type',
  },
  loanType: {
    label: 'Loan Type',
    type: 'select',
    options: [
      'Home',
      'Personal',
      'Car',
      'Education',
      'Reduce my EMI',
      'Conversion of multiple loans',
      'SME (up to 50 crores) & MSME (up to 10 crores)',
      'Small Business Loan',
      'Loan against property',
      'Gold Loan',
      'Other',
    ],
    required: true,
    conditional: (data: { category: string }) => data.category === 'Loan',
    placeholder: 'Enter loan type',
  },
  insuranceType: {
    label: 'Insurance Type',
    type: 'select',
    options: ['Term Insurance', 'Health Insurance', 'Both', 'Other'],
    required: true,
    conditional: (data: { category: string }) => data.category === 'Insurance',
    placeholder: 'Enter insurance type',
  },
  healthCondition: {
    label: 'Health Condition',
    type: 'select',
    options: ['Diabetes', 'Blood Pressure', 'Heart Disease', 'Other', 'None'],
    conditional: (data: { category: string }) => data.category === 'Insurance',
    placeholder: 'Enter health condition',
  },
  residentialStatus: {
    label: 'Residential Status',
    type: 'select',
    options: ['Indian', 'NRI', 'PIO', 'OCI', 'Other'],
    conditional: (data: { category: string }) => data.category === 'Insurance',
    placeholder: 'Enter residential status',
  },
  lifeStyleHabits: {
    label: 'Lifestyle Habits',
    type: 'select',
    options: ['Smoking or Drinking', 'Healthy', 'Other'],
    conditional: (data: { category: string }) => data.category === 'Insurance',
    placeholder: 'Enter lifestyle habits',
  },
  review_status: {
    label: 'Review Status',
    type: 'select',
    defaultValue: 'pending',
    placeholder: 'Enter review status',
    options: ['pending', 'reviewed', 'call scheduled', 'completed'],
  },
  status: {
    label: 'Status',
    type: 'select',
    defaultValue: 'open',
    options: ['open', 'closed', 'inprogress', 'canceled'],
    placeholder: 'Enter status',
  },
  callSchedule: {
    label: 'Call Schedule',
    type: 'date',
    placeholder: 'Select call schedule date',
  },
  delayInPayment: {
    label: 'Yes',
    type: 'checkbox',
    conditional: (data: { category: string }) => data.category === 'Loan',
    placeholder: 'Is there a delay in payment?',
  },
  cibilIssues: {
    label: 'Yes',
    type: 'checkbox',
    conditional: (data: { category: string }) =>
      ['Loan'].includes(data.category),
    placeholder: 'Any Cibil issues?',
  },
  isKnownCoverage: {
    label: 'Yes',
    type: 'checkbox',
    conditional: (data: { category: string }) => data.category === 'Insurance',
    placeholder: 'Lead has known coverage?',
  },
  differentlyAbled: {
    label: 'Yes',
    type: 'checkbox',
    conditional: (data: { category: string }) => data.category === 'Insurance',
    placeholder: 'Is the lead differently abled?',
  },
  isIncomeTaxFiled: {
    label: 'Yes',
    type: 'checkbox',
    conditional: (data: { category: string }) => data.category === 'Insurance',
    placeholder: 'Is income tax filed?',
  },
  note: {
    label: 'Customer Notes',
    type: 'textarea',
    placeholder: 'Enter customer notes',
  },
  comment: { label: 'Comment', type: 'textarea', placeholder: 'Enter comment' },
};
