export function createLeadModel(data) {
  return {
    full_Name: data?.full_Name || '',
    mobile: data?.mobile || '',
    mobileTwo: data?.mobileTwo || '',
    email: data?.email || '',
    dob: data?.dob || '',
    age: data?.age || '',
    gender: data?.gender || '',
    annualIncome: data?.annualIncome || '',
    employmentType: data?.employmentType || '',
    street: data?.address?.street || '',
    zipCode: data?.address?.zipCode || '',
    city: data?.address?.city || '',
    state: data?.address?.state || '',
    country: data?.address?.country || '',
    photo: data?.photo || null,
    category: data?.category || '',
    sub_category: data?.sub_category || '',
    lead_from: data?.lead_from || '',
    review_status: data?.review_status || 'pending',
    converted: data?.converted || false,
    note: data?.note || [],
    referral_id: data?.referral_id || '',
    referral_name: data?.referral_name || '',
    created_by_id: data?.created_by_id || '',
    created_by_name: data?.created_by_name || '',
    created_at: new Date(),
    updated_at: new Date(),
    updated_by_id: data?.updated_by_id || '',
    updated_by_name: data?.updated_by_name || '',
    updated_history: [],
    panNumber: data?.panNumber || '',
    aadharNumber: data?.aadharNumber || '',
    filingType: data?.filingType || [],
    loanType: data?.loanType || '',
    delayInPayment: data?.delayInPayment || false,
    insuranceType: data?.insuranceType || [],
    isKnownCoverage: data?.isKnownCoverage || false,
    healthCondition: data?.healthCondition || '',
    differentlyAbled: data?.differentlyAbled || false,
    lifeStyleHabits: data?.lifeStyleHabits || '',
    isIncomeTaxFiled: data?.isIncomeTaxFiled || false,
    residentialStatus: data?.residentialStatus || '',
    status: data?.status || 'open',
    callSchedule: data?.callSchedule || '',
    callScheduleHistory: [],
    comment: data?.comment || '',
    commentHistory: [],
    isCustomer: data?.isCustomer || false,
    customer_id: data?.customer_id || '',
    customer_name: data?.customer_name || '',
  };
}
